export interface IResource {
  coach_name: string,
  coach_id?: string,
  description: string,
  downloads: number,
  file_link?: string,
  gender: string,
  group: string,
  id?: string,
  level: string,
  name: string,
  rating: number,
  size: number,
  type: string,
}